### ISSUE TITLE
Build project with TBB using Intel Compiler 16 is failed

### ISSUE THREAD

**Issue by Semen52** [01org/tbb#26]
Build the project on Windows using Intel Compiler 16:
tbb/machine/msvc_ia32_common.h(69): error #1879: unimplemented pragma ignored 
               __TBB_MACHINE_DEFINE_ATOMICS(1,8,char,__int8)
With VC this problem isn't observed.

**Comment by alexey-katranov** [comment]
Could you provide a reproducer and/or more details about versions of used products, please? E.g. Intel TBB version, VC version and so on. The issue seems untypical because [Intel(R) C++ Compiler 16.0](https://github.com/01org/tbb/blob/tbb_2017/doc/Release_Notes.txt#L84) is an officially supported compiler and [test_atomic.cpp](https://github.com/01org/tbb/blob/tbb_2017/src/test/test_atomic.cpp) should work with it.

**Comment by Semen52** [comment]
I've build TBB using this version: Commit: eb6336ad29450f2a64af5123ca1b9429ff6bc11d [eb6336a] (Committing Intel(R) TBB 2017 Update 7 source code) and visual studio 2015 (Update 3).
After that I'm linking tbb.lib to my project in VS2015 and trying to build using Intel(R) C++ Compiler 16.0.
It fails:
msvc_ia32_common.h(69): error #1879: unimplemented pragma ignored
__TBB_MACHINE_DEFINE_ATOMICS(1,8,char,__int8)
msvc_ia32_common.h(70): error #1879: unimplemented pragma ignored
__TBB_MACHINE_DEFINE_ATOMICS(2,16,short,__int16)
...
msvc_ia32_common.h(197): error #1879: unimplemented pragma ignored
#pragma intrinsic(__rdtsc)
icl: : error #10298: problem during post processing of parallel object compilation

**Comment by Semen52** [comment]
I've found one topic https://software.intel.com/en-us/forums/intel-c-compiler/topic/278366, but it doesn't contains the solution.

**Comment by ntfshard** [comment]
Hello
Could you please check compatibility of your installed update of Intel(R) C++ Compiler 16.0 with your Visual Studio 2015 update 3. They can be incompatible (VS can be newer than Intel(R) C++ Compiler).

Try to install the latest update of Intel(R) C++ Compiler OR try to use it with older VS compiler.

**Comment by vladimir-polin** [comment]
Hello,

Intel Compiler 16.0 does not support VS2015 update 3. You need Intel Compiler 17.0 update 4 for this version of Visual Studio.

--Vladimir

**Comment by tbbdev** [comment]
Not a bug. Environment problem.
Closed.
